#users_ms
### prueba
GET http://127.0.0.1:8000/test

### Login (Administrador)
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "admin@system.com",
  "password": "admin123"
}

### Login (Gestor)
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "gestor@system.com",
  "password": "gestor123"
}

### Validar Token
GET http://127.0.0.1:8000/auth/validate
Authorization: Bearer 8ed926b8

### Cerrar Sesión
POST http://127.0.0.1:8000/auth/logout
Authorization: Bearer 8ed926b8

### Listar todos los usuarios
GET http://127.0.0.1:8000/users
Authorization: Bearer d792a983

### Ver usuario específico
GET http://127.0.0.1:8000/user/1
Authorization: Bearer 6b01237c

### Crear nuevo usuario (Gestor)
POST http://127.0.0.1:8000/users
Authorization: Bearer d792a983
Content-Type: application/json

{
  "name": "Juan Perez",
  "email": "juan@test.com",
  "password": "123456",
  "role": "gestor"
}

### Crear nuevo usuario (Administrador)
POST http://127.0.0.1:8000/users
Authorization: Bearer 4b591b98
Content-Type: application/json

{
  "name": "Maria Garcia",
  "email": "maria@test.com",
  "password": "123456",
  "role": "administrador"
}

### Actualizar usuario
PUT http://127.0.0.1:8000/users/3
Authorization: Bearer 
Content-Type: application/json

{
  "name": "Juan Pérez Actualizado",
  "email": "juan.nuevo@test.com",
  "password": "nueva123"
}

### Actualizar solo el rol
PUT http://127.0.0.1:8000/users/3
Authorization: Bearer 
Content-Type: application/json

{
  "role": "administrador"
}

### Eliminar usuario
DELETE http://127.0.0.1:8000/users/3
Authorization: Bearer 